-- Insert market data
INSERT INTO MARKET (ID, OTHER_COLUMNS) VALUES (1, 'Default Market 1');
INSERT INTO MARKET (ID, OTHER_COLUMNS) VALUES (2, 'Default Market 2');

-- Insert product data with valid categories
INSERT INTO PRODUCT (NAME, CATEGORY, PRICE, DESCRIPTION, BARCODE)
VALUES ('Samsung Galaxy S21', 'ELECTRONICS', 80.99, 'Latest Samsung Galaxy S21 with 128GB storage and 8GB RAM', '1234567890123');
INSERT INTO PRODUCT (NAME, CATEGORY, PRICE, DESCRIPTION, BARCODE)
VALUES ('Iphone 14 pro', 'ELECTRONICS', 1000.23, '''Apple iPhone 14 Pro with 128GB storage and 6GB RAM', '9876543210987');


-- Insert stock data
INSERT INTO STOCK (QUANTITY, MARKET_ID, PRODUCT_ID)
VALUES (100, 1, 1);
INSERT INTO STOCK (QUANTITY, MARKET_ID, PRODUCT_ID)
VALUES (200, 1, 2);
INSERT INTO STOCK (QUANTITY, MARKET_ID, PRODUCT_ID)
VALUES (150, 2, 1);
INSERT INTO STOCK (QUANTITY, MARKET_ID, PRODUCT_ID)
VALUES (50, 2, 2);
